config/routes.rb
Checkpoint::Application.routes.draw do

  root "homes#show"

  resource :dashboard, only: [:show]

  resources :goals do
    resources :steps, only: [:new, :create, :index]
    resources :review_requests, only: [:new, :create]
  end

  resources :steps, only: [:edit, :update, :destroy]

  resources :athletes, only: [:index]

  resources :review_requests, only: [:index, :show]

  resources :users, only: [:show] do
    member do
      post "/coach" => "coaching_relationships#create"
      delete "/stopcoach" => "coaching_relationships#destroy"
    end
  end

end

app/models/check_to_complete.rb
class CheckToComplete < ActionView::Helpers::FormBuilder
  def check_to_complete
    check_box(
      :status,
      { onchange: "this.form.submit_button.click();" },
      checked_value = "completed"
    )
  end

  def hidden_submit
    submit(
      "Update",
      id: "submit_button",
      style: "display: none"
    )
  end
end

app/models/coaching_relationship.rb
class CoachingRelationship < ActiveRecord::Base
  belongs_to :coach, class_name: "User"
  belongs_to :athlete, class_name: "User"

  validates :coach_id,
    uniqueness: { scope: :athlete_id }
    
  validate :cannot_coach_yourself
  
  private
  
  def cannot_coach_yourself
    if coach_id == athlete_id
      errors.add(:base, "You cannot coach yourself.")
    end
  end
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :steps, dependent: :destroy
  has_many :review_requests, dependent: :destroy
  validates :description, presence: true
  validates :target_date, presence: true

  def completed?
    status == "completed"
  end

  def set_date_completed
    if completed?
      update(completed_on: Date.today)
    end
  end

  def current_steps
    steps.where(status: "current")
  end

  def completed_steps
    steps.where(status: "completed")
  end

  def has_steps?
    steps != []
  end

  def has_open_review?
    review_requests != []
  end
end

app/models/review_request.rb
class ReviewRequest < ActiveRecord::Base
  belongs_to :athlete, class_name: "User"
  belongs_to :coach, class_name: "User"
  belongs_to :goal

  validates :coach_id, presence: true
  validates :athlete_id, presence: true
  validates :goal_id, presence: true

  def goal_steps
    goal.steps
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :goal
  validates :description, presence: true
  validates :target_date, presence: true

  def completed?
    status == "completed"
  end

  def set_date_completed
    if completed?
      update(completed_on: Date.today)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User  
  has_many :goals, dependent: :destroy
  has_many :steps, through: :goals

  has_many :coach_to_athlete_relationships,
    foreign_key: :coach_id,
    class_name: "CoachingRelationship",
    dependent: :destroy
  has_many :athletes, through: :coach_to_athlete_relationships

  has_many :athlete_to_coach_relationships,
    foreign_key: :athlete_id,
    class_name: "CoachingRelationship",
    dependent: :destroy
  has_many :coaches, through: :athlete_to_coach_relationships

  has_many :review_requests, foreign_key: :athlete_id
  has_many :review_requests, foreign_key: :coach_id

  def current_goals
    goals.where(status: "current")
  end

  def completed_goals
    goals.where(status: "completed")
  end

  def owns_step?(step)
    steps.include? step
  end

  def owns_goal?(goal)
    goals.include? goal
  end

  def coach(athlete)
    coach_to_athlete_relationships.create(athlete_id: athlete.id)
  end

  def coaching?(athlete)
    athlete_ids.include? athlete.id
  end

  def uncoach(athlete)
    athletes.destroy athlete
  end

  def has_coaches?
    coaches != []
  end

  def coaches_athletes?
    athletes != []
  end

  def has_coach_reviews?
    review_requests != []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  
  def index
    @athletes = current_user.athletes
  end
  
end

app/controllers/coaching_relationships_controller.rb
class CoachingRelationshipsController < ApplicationController
  def create
    @user = User.find(params[:id])
    current_user.coach @user
  end
  
  def destroy
    @user = User.find(params[:id])
    current_user.uncoach @user
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @users = User.all
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @current_goals = current_user.current_goals
    @completed_goals = current_user.completed_goals
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if !@goal.save
      render :new
    end
  end

  def show
    @goal = find_goal
    @current_steps = @goal.current_steps
    @completed_steps = @goal.completed_steps
  end

  def edit
    @goal = find_goal
  end

  def update
    @goal = find_goal
    @goal.update(goal_params)
    @goal.set_date_completed
  end

  def destroy
    @goal = find_goal
    @goal.destroy
  end

  private

  def find_goal
    Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(
      :description,
      :target_date,
      :status
    )
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  before_action :goto_dashboard, if: :signed_in?

  def show
  end

  private

  def goto_dashboard
    redirect_to dashboard_path
  end

end

app/controllers/review_requests_controller.rb
class ReviewRequestsController < ApplicationController
  
  def index
    @review_requests = current_user.review_requests
  end

  def new
    @reviewable_goal = Goal.find(params[:goal_id])
    @review_request = @reviewable_goal.review_requests.new
  end

  def create
    @reviewable_goal = Goal.find(params[:goal_id])
    @reviewable_goal.review_requests.create(review_request_params)
  end
  
  def show
    @review_request = ReviewRequest.find(params[:id])
    @goal = @review_request.goal
  end

  private

  def review_request_params
    params.require(:review_request).permit(
      :body,
      :coach_id
    ).merge(
      athlete_id: current_user.id
    )
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  def new
    @goal = find_goal
    @step = @goal.steps.new
  end

  def create
    @goal = find_goal
    @step = @goal.steps.new(step_params)
    if !@step.save
      render :new
    end
  end

  def edit
    @step = find_step
  end

  def update
    @step = find_step
    @step.update(step_params)
    @step.set_date_completed
  end

  def destroy
    @step = find_step
    @step.destroy
  end

  private

  def find_goal
    Goal.find(params[:goal_id])
  end

  def find_step
    Step.find(params[:id])
  end

  def step_params
    params.require(:step).permit(
      :description,
      :target_date,
      :status
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form_errors.html.erb
<div id="form_errors">
  <% if target.errors.any? %>

    <p>Could not save for the following reasons:</p>

    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  <% end %>
</div>

<%= yield %>

app/views/athletes/index.html.erb
<h1>Athletes Coached</h1>
<div>
  <%= render @athletes %>
</div>

app/views/coaching_relationships/create.js.erb
$('#coaching-button').html("<%= j button_to 'Stop Coaching', stopcoach_user_path(@user), method: :delete, remote: true %>");

app/views/coaching_relationships/destroy.js.erb
$('#coaching-button').html("<%= j button_to 'Coach', coach_user_path(@user), remote: true %>");

app/views/dashboards/show.html.erb
<h1>Other Active Users</h1>
<div>
  <%= render @users %>
</div>

app/views/goals/_completed_goal.html.erb
<div class="completed-goal">
  <%= div_for(completed_goal) do %>
    <h3>Goal: <%= completed_goal.description %></h3>
    <p>Completed on: <%= time_tag(completed_goal.completed_on) %></p>
    <p><%= link_to "Remove this Goal", completed_goal, method: :delete, confirm: "Really? Remove this Goal?", remote: true %></p>
  <% end %>
</div>

app/views/goals/_current_goal.html.erb
<div class="current-goal">
  <%= div_for(current_goal) do %>
    <p>
      <div class="item-header" id="goal-header">
        <h3 class="item-header-text" id="goal-header-text">Goal</h3>
      </div>
      <div class="x-to-delete">
        <%= link_to "x", current_goal, method: :delete, confirm: "Really? Remove this Goal?", remote: true %>
      </div>
      <h3 id="goal-description"><%= current_goal.description %></h3>
      Target Day: <%= time_tag(current_goal.target_date) %>
      <%= link_to "(edit)", [:edit, current_goal], remote: true %>

      <% if current_user.owns_goal? current_goal %>
        <div class="goal_step_links">
          Goal Steps: <%= link_to "Add", [:new, current_goal, :step], id: "new_goal_step", remote: true %>
          <% if current_goal.has_steps? %>
            <%= link_to "View", current_goal %>
          <% end %>
        </div>

        <%= form_for current_goal, builder: CheckToComplete, remote: true do |form| %>
          Complete: <%= form.check_to_complete %>
          <%= form.hidden_submit %>
        <% end %>
        <% if current_user.has_coaches? %>
          <div class="button">
            <% if current_goal.has_open_review? %>
              <%= link_to "Review Open", current_goal %>
            <% else %>
              <%= link_to "Request Review", [:new, current_goal, :review_request], remote: true %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/goals/_edit.html.erb
<div id="content-wrapper">
  <div id="edit_goal_form", class="form-pop">
    <h2>Edit this Goal</h2>
    <div class="form">
      <%= form_for @goal, remote: true do |form| %>
        <%= render "form_errors", target: @goal %>
        <div><%= form.text_area :description, placeholder: "Goal" %></div>
        <div><%= form.label "Target Date:" %></div>
        <div><%= form.date_field :target_date %></div>
        <div><%= form.submit "Update" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/goals/_goal_basic.html.erb
<div class="current-goal">
  <%= div_for(goal_basic) do %>
    <p>
      <div class="item-header" id="goal-header">
        <h3 class="item-header-text" id="goal-header-text">Goal</h3>
      </div>
      <h3 id="goal-description"><%= goal_basic.description %></h3>
      Target Day: <%= time_tag(goal_basic.target_date) %>
    </p>
  <% end %>
</div>

app/views/goals/_new.html.erb
<div id="content-wrapper">
  <div id="new_goal_form", class="form-pop">
    <h2>New Goal</h2>
    <div class="form">
      <%= form_for @goal, remote: true do |form| %>
        <%= render "form_errors", target: @goal %>
        <div><%= form.text_area :description, placeholder: "Goal" %></div>
        <div><%= form.label "Target Date:" %></div>
        <div><%= form.date_field :target_date %></div>
        <div><%= form.submit "Add Goal" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/goals/_new_goal.html.erb
<div class="new-goal">
  <div class="goal", id="new">
    <div class="item-header" id="goal-header">
      <h3 class="item-header-text" id="goal-header-text">Goal</h3>
    </div>
    <h3 id="goal-description"><%= link_to "(new)", new_goal_path, remote: true %></h3>
  </div>
</div>

app/views/goals/create.js.erb
$("#content-wrapper").animate({
    marginBottom: "0in"
  }, 400 );
$('#new_goal_form').fadeOut(400);
$('<%= j render partial: "current_goal", object: @goal %>').insertBefore( ".new-goal" );

app/views/goals/destroy.js.erb
$("#<%= dom_id(@goal) %>").remove();

app/views/goals/edit.js.erb
$('#content-wrapper').remove();
$('#current_goals').before('<%= j render "edit" %>');
$('#content-wrapper').animate({
    opacity: 0.96,
    marginTop: '-0.4in'
  }, 400 );

app/views/goals/index.html.erb
<h2>Current Goals</h2>

<div id="current_goals">
  <%= render partial: "current_goal", collection: @current_goals %>
  <%= render partial: "new_goal" %>
</div>

<h2>Completed</h2>

<div id="completed_goals">
  <%= render partial: "completed_goal", collection: @completed_goals %>
</div>

app/views/goals/new.js.erb
$('#content-wrapper').remove();
$('#current_goals').before('<%= j render "new" %>');
$('#content-wrapper').animate({
    opacity: 0.96,
    marginTop: '-0.4in'
  }, 400 );

app/views/goals/show.html.erb
<h1>Checkpoints</h1>

<div id="current_goals">
  <%= render partial: 'goal_basic', object: @goal %>
</div>

<h2>Checkpoints for this goal</h2>

<div id="current_steps">
  <%= render partial: 'steps/current_step', collection: @current_steps %>
  <%= render partial: "steps/new_step" %>
</div>

<h2>Completed</h2>

<div id="completed_steps">
  <%= render partial: 'steps/completed_step', collection: @completed_steps %>
</div>

app/views/goals/update.js.erb
<% if @goal.completed? %>
  $("#<%= dom_id(@goal) %>").slideUp();
	$("#<%= dom_id(@goal) %>").remove();
  $("#completed_goals").append("<%= j render partial: 'completed_goal', object: @goal %>");
<% else %>
  $("#content-wrapper").animate({
    marginBottom: "0in"
  }, 400 );
  $('#edit_goal_form').fadeOut(400);
  $("#<%= dom_id(@goal) %>").remove();
  $('<%= j render partial: "current_goal", object: @goal %>').insertBefore( ".new-goal" );
<% end %>

app/views/homes/show.html.erb
<h1>Wecome to Checkpoint!</h1>

<div class="welcome">
  <p>Checkpoint is an interactive goal setting app designed for fitness, Crossfit in my case.  The idea is that people should be able to set goals, break them down into smaller gaol steps or "checkpoints" and check them off as each goal/checkpoint is reached.</p>

  <p>If you have a coaching relationship with another user, your goals have added functionality where you can send a review request to your coach and they can see and edit your checkpoints associated with that goal or create new ones.</p>

  <p>For demo purposes I have an account set up u: athlete@athlete.com p: athlete</p>

  <p>Please feel free to try it out or create accounts of your own. I intend to continue development on this app after I have acquired added expeience and skills in javascript frameworks. Right now I'm simply using *.js.erb files for DOM manipulation.</p>

  <p>~Jeremy Salig 6.30.14</p>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkpoint</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="main-body">

<ul class="nav">
  <% if signed_in? %>
    <li><%= link_to 'Home', dashboard_path %></li>
    <li><%= link_to 'Goals', goals_path %></li>
    <% if current_user.coaches_athletes? %>
      <li><%= link_to 'Athletes', athletes_path %></li>
      <li><%= link_to 'Coach Reviews', review_requests_path %></li>
    <% end %>
    <li id="sign-out"><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
  <% else %>
    <li id="sign-in"><%= link_to 'Sign in', sign_in_path %></li>
  <% end %>
</ul>

  <% if signed_in? %>
    <p id="signed-in-as">Signed in as: <%= current_user.email %></p>
  <% end %>

  <div id="flash">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>

<div>
  <%= yield %>
</div>

</body>
</html>

app/views/review_requests/_new.html.erb
<div id="content-wrapper">
  <div id="new_review_request_form", class="form-pop">
    <h2>New Review Request</h2>
    <div>
      <h3>Goal</h3>
      <%= @reviewable_goal.description %> by
      <%= time_tag(@reviewable_goal.target_date) %>
      <h3>Checkpoints</h3>
      <ul>
        <%= render partial: 'reviewable_step', collection: @reviewable_goal.steps %>
      </ul>
    </div>

    <div class="form">
      <%= form_for [@reviewable_goal, @review_request], remote: true do |form| %>
        For coach: <%= form.collection_select :coach_id, current_user.coaches, :id, :email %><br>
        <%= form.text_area :body, placeholder: "Comment on this Goal" %><br>
        <%= form.submit "Send Review Request" %>
      <% end %>
    </div>
  </div>
</div>

app/views/review_requests/_review_request.html.erb
<div>
  <%= div_for(review_request) do %>
    <p>Athlete: <%= review_request.athlete.email %></p>
    Date: <%= time_tag(review_request.created_at) %>
    <h3>Goal</h3>
    <%= review_request.goal.description %> by 
    <%= time_tag(review_request.goal.target_date) %>
    <h3>Checkpoints</h3>
    <ul>
      <%= render partial: 'reviewable_step', collection: review_request.goal_steps %>
    </ul>
    <%= link_to "Review and Respond", review_request %>
  <% end %>
</div>

app/views/review_requests/_reviewable_step.html.erb
<li>
  <%= reviewable_step.description %> by
  <%= time_tag(reviewable_step.target_date) %>
</li>

app/views/review_requests/create.js.erb
$("#content-wrapper").animate({
    marginBottom: "0in"
  }, 400 );
$('#new_review_request_form').remove();

app/views/review_requests/index.html.erb
<h1>Review Requests</h1>

<div id="review_requests">
  <%= render @review_requests %>
</div>

app/views/review_requests/new.js.erb
$('#content-wrapper').remove();
$('#current_goals').before('<%= j render "new" %>');
$('#content-wrapper').animate({
    opacity: 0.96,
    marginTop: '-0.4in'
  }, 400 );

app/views/review_requests/show.html.erb
<h2>Review requested by <%= @review_request.athlete.email %></h2>

<nav class="nav_bar">
  <%= link_to "Finished Reviewing", review_requests_path %>
</nav>

<p><%= @review_request.body %></p>

<div id="current_goals">
  <%= render partial: 'goals/goal_basic', object: @goal %>
</div>

<div class="goal_step_links">
  <h2>Checkpoints for this goal</h2>
  <div class="new-item"><%= link_to "+", [:new, @goal, :step], id: "new_link", remote: true %></div>
  <div id="current_steps">
    <%= render partial: 'steps/current_step', collection: @goal.current_steps %>
    <%= render partial: "steps/new_step" %>
  </div>

  <h2>Completed</h2>

  <div id="current_steps">
    <%= render partial: 'steps/completed_step', collection: @goal.completed_steps %>
  </div>
</div>

app/views/steps/_completed_step.html.erb
<div class="completed-goal">
  <%= div_for(completed_step) do %>
    <h3>Step: <%= completed_step.description %></h3>
    <p>Completed on: <%= time_tag(completed_step.completed_on) %></p>

    <% if current_user.owns_step? completed_step %>
      <p><%= link_to "Remove this Step", completed_step, method: :delete, confirm: "Really? Remove this Step?", remote: true %></p>
    <% end %>
  <% end %>
</div>

app/views/steps/_current_step.html.erb
<div class="current-goal">
  <%= div_for(current_step) do %>
	<div class="item-header" id="step-header">
    <h3 class="item-header-text" id="step-header-text">Checkpoint</h3>
  </div>
	  <div class="x-to-delete">
	    <%= link_to "x", current_step, method: :delete, confirm: "Really? Remove this Checkpoint?", remote: true %>
	  </div>
    <h3 id="goal-description"><%= current_step.description %></h3>
    Target Day: <%= time_tag(current_step.target_date) %>
    <%= link_to "(edit)", [:edit, current_step], remote: true %>

    <% if current_user.owns_step? current_step %>
      <%= form_for current_step, builder: CheckToComplete, remote: true do |form| %>
        Complete: <%= form.check_to_complete %>
        <%= form.hidden_submit %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/steps/_edit.html.erb
<div id="content-wrapper">
  <div id="edit_goal_step_form", class="form-pop">
    <h2>Edit Step for this Goal</h2>
    <div class="form">
      <%= form_for [@goal, @step], remote: true do |form| %>
        <%= render "form_errors", target: @step %>
        <div><%= form.text_area :description, placeholder: "Goal Step" %></div>
        <div><%= form.label "Target Date:" %></div>
        <div><%= form.date_field :target_date %></div>
        <div><%= form.submit "Update" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/steps/_new.html.erb
<div id="content-wrapper">
  <div id="new_goal_step_form", class="form-pop">
    <h2>New Step</h2>
    <div class="form">
      <%= form_for [@goal, @step], remote: true do |form| %>
        <%= render "form_errors", target: @step %>
        <div><%= form.text_area :description, placeholder: "Goal Step" %></div>
        <div><%= form.label "Target Date:" %></div>
        <div><%= form.date_field :target_date %></div>
        <div><%= form.submit "Add Goal Step" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/steps/_new_step.html.erb
<div class="new-step">
  <div class="goal", id="new">

      <div class="item-header" id="step-header">
        <h3 class="item-header-text" id="step-header-text">Checkpoint</h3>
      </div>
      <h3 id="goal-description"><%= link_to "(new)", [:new, @goal, :step], id: "new_link", remote: true %></h3>

  </div>
</div>

app/views/steps/create.js.erb
$("#content-wrapper").animate({
    marginBottom: "0in"
  }, 400 );
$('#new_goal_step_form').fadeOut(200);
<% if @goal.steps.count == 1 %>
  $('#<%= dom_id(@goal) %> .goal_step_links').append('<%= j link_to "View", @goal %>');
<% end %>
$('<%= j render partial: "current_step", object: @step %>').insertBefore( ".new-step" );

app/views/steps/destroy.js.erb
$("#<%= dom_id(@step) %>").remove();

app/views/steps/edit.js.erb
$('#content-wrapper').remove();
$('#current_goals').before('<%= j render "edit" %>');
$('#content-wrapper').animate({
    opacity: 0.96,
    marginTop: '-0.4in'
  }, 400 );

app/views/steps/new.js.erb
$('#content-wrapper').remove();
$('#current_goals').before('<%= j render "new" %>');
$('#content-wrapper').animate({
    opacity: 0.96,
    marginTop: '-0.4in'
  }, 400 );

app/views/steps/update.js.erb
<% if @step.completed? %>
  $("#<%= dom_id(@step) %>").slideUp();
  $("#<%= dom_id(@step) %>").remove();
  $("#completed_steps").append("<%= j render partial: 'completed_step', object: @step %>");
<% else %>
  $("#content-wrapper").animate({
    marginBottom: "0in"
  }, 400 );
  $('#edit_goal_step_form').fadeOut(400);
  $("#<%= dom_id(@step) %>").remove();
  $('<%= j render partial: "current_step", object: @step %>').insertBefore( ".new-step" );
<% end %>

app/views/users/_completed_goal.html.erb
<div>
  <%= completed_goal.description %><br>
  Completed on: <%= time_tag(completed_goal.completed_on) %>
</div>
<br>

app/views/users/_current_goal.html.erb
<div>
  <%= current_goal.description %><br>
  Target Date: <%= time_tag(current_goal.target_date) %>
</div>

app/views/users/_user.html.erb
<%= div_for(user) do %>
  <p>Athlete: <%= link_to user.email, user %></p>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %>'s Profile</h1>

<div id="coaching-button">
  <% if current_user.coaching? @user %>
    <%= button_to "Stop Coaching", stopcoach_user_path(@user), method: :delete,  remote: true %>
  <% else %>
    <%= button_to "Coach", coach_user_path(@user), remote: true %>
  <% end %>
</div>

<h2>Current</h2>

<%= render partial: 'current_goal', collection: @user.current_goals %>

<h2>Completed</h2>

<%= render partial: 'completed_goal', collection: @user.completed_goals %>